# Generated by Django 4.1.3 on 2023-06-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discontact',
            name='companyaddress',
            field=models.TextField(max_length=1000, null=True, verbose_name='companyaddress'),
        ),
        migrations.AlterField(
            model_name='discontact',
            name='companyemail',
            field=models.EmailField(max_length=255, null=True, verbose_name='companyemail'),
        ),
        migrations.AlterField(
            model_name='discontact',
            name='personalemail',
            field=models.EmailField(max_length=255, null=True, verbose_name='personalemail'),
        ),
    ]
