# Generated by Django 4.1.3 on 2023-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_image_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='awards/files/covers'),
        ),
    ]
