# Generated by Django 4.1.3 on 2023-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(max_length=500, null=True, verbose_name='Details')),
            ],
            options={
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='details',
        ),
    ]
